<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.18" />
    <PackageReference Include="DuonDevKit.Core" Version="0.8.0" />
    <PackageReference Include="DuonDevKit.EntityFrameworkCore" Version="0.7.0" />
    <PackageReference Include="DuonDevKit.AspNetCore" Version="0.4.0" />
<!--#if (dapper)
    <PackageReference Include="DuonDevKit.Dapper" Version="0.2.0" />
#endif-->
<!--#if (auth)
    <PackageReference Include="DuonDevKit.Jwt" Version="0.3.0" />
#endif-->
<!--#if (validation)
    <PackageReference Include="DuonDevKit.Validation" Version="0.2.0" />
#endif-->
  </ItemGroup>

</Project>
