<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DuonDevKit.AspNetCore\DuonDevKit.AspNetCore.csproj" />
    <ProjectReference Include="..\..\DuonDevKit.Dapper\DuonDevKit.Dapper.csproj" />
    <ProjectReference Include="..\..\DuonDevKit.EntityFrameworkCore\DuonDevKit.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\DuonDevKit.Jwt\DuonDevKit.Jwt.csproj" />
  </ItemGroup>

</Project>
